
spring:
  application:
    name=fmcg-campaign:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/fmcg_campaign?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: never

  security:
    jwt:
      secret: VGhpc0lzQVNlY3VyZVNlY3JldEtleUZvckpXVEF1dGgxMjM0NTY3ODkw
      expiration-seconds: 3600